spring:
  application:
    name: shipment-anomaly-detector-api
  datasource:
    url: jdbc:postgresql://localhost:5433/shipment_anomaly_db
    username: smit
    password: smit123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
